# Generated by Django 3.1.7 on 2021-04-09 04:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hawc.usermanager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('q_author', models.BooleanField(default=False)),
                ('sign_safe', models.BooleanField(default=False)),
                ('valid', models.DateField(null=True)),
                ('name_full', models.CharField(blank=True, max_length=30)),
                ('name_swapped', models.CharField(blank=True, max_length=30)),
                ('initialed_full', models.CharField(blank=True, max_length=30)),
                ('initialed_swapped', models.CharField(blank=True, max_length=30)),
                ('web_page', models.CharField(blank=True, max_length=40)),
                ('activities', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', hawc.usermanager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('principal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('webpage', models.CharField(max_length=50)),
                ('publications', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('journal', models.CharField(max_length=30)),
                ('signup_due', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=40)),
                ('principal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=40)),
                ('service', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accept'), ('R', 'Reject')], max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hawc.paper')),
            ],
            options={
                'unique_together': {('paper', 'author')},
            },
        ),
        migrations.AddField(
            model_name='author',
            name='emails',
            field=models.ManyToManyField(to='hawc.Email'),
        ),
        migrations.AddField(
            model_name='author',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='author',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hawc.institution'),
        ),
        migrations.AddField(
            model_name='author',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hawc.major'),
        ),
        migrations.AddField(
            model_name='author',
            name='paper',
            field=models.ManyToManyField(through='hawc.Publication', to='hawc.Paper'),
        ),
        migrations.AddField(
            model_name='author',
            name='phones',
            field=models.ManyToManyField(to='hawc.Phone'),
        ),
        migrations.AddField(
            model_name='author',
            name='socials',
            field=models.ManyToManyField(to='hawc.Social'),
        ),
        migrations.AddField(
            model_name='author',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
