# Generated by Django 3.1.7 on 2021-04-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawc', '0002_auto_20210410_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='principal',
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
