# Generated by Django 3.1.7 on 2021-04-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawc', '0004_auto_20210414_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='sign_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
